CREATE TABLE CREDENTIAL (
	USERNAME VARCHAR(30) NOT NULL,
	RESID INTEGER NOT NULL,
	PASSWORDHASH VARCHAR(200) NOT NULL,
	REGISTRATIONDATE DATE NOT NULL,
	PRIMARY KEY (USERNAME),
	CONSTRAINT FK_CREDENTIAL_RESIDENT FOREIGN KEY (RESID) REFERENCES RESIDENT(RESID)
);
