CREATE TABLE ELECTRICITY (
	USAGEID INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1), 
	RESID INTEGER NOT NULL,
	USAGEDATE DATE NOT NULL,
	USAGEHOUR INTEGER NOT NULL,
	FRIDGEUSAGE DECIMAL(2,1) NOT NULL,
	ACUSAGE DECIMAL(2,1) NOT NULL,
	WMUSAGE DECIMAL(2,1) NOT NULL,
	TEMPERATURE INTEGER NOT NULL,
	PRIMARY KEY (USAGEID),
	CONSTRAINT FK_ELECTRICITY_RESIDENT FOREIGN KEY (RESID) REFERENCES RESIDENT(RESID),
	CONSTRAINT CK_HOUR CHECK (USAGEHOUR >= 0 AND USAGEHOUR <= 23)
);
