CREATE TABLE RESIDENT (
	RESID INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
	FIRSTNAME VARCHAR(30) NOT NULL, 
	SURENAME VARCHAR(30) NOT NULL, 
	DOB DATE NOT NULL, 
	ADDRESS VARCHAR(50) NOT NULL, 
	POSTCODE DECIMAL(4) NOT NULL, 
	EMAIL VARCHAR(30) NOT NULL, 
	MOBILE VARCHAR(12) NOT NULL, 
	NUMBEROFRESIDENT INTEGER NOT NULL, 
	ENERGYPROVIDER VARCHAR(20) NOT NULL, 
	PRIMARY KEY (RESID)
);
